Добавил роут для json мода и файл для запуска апи
ManVersusPerson/yolo_animal_detection pull request #3
Opened 2023-05-28 19:01 UTC by amoonnra

2023-05-28 19:02 UTC, amoonnra commented
- [ ] #2

2023-05-29 18:55 UTC, ManVersusPerson requested changes
Не надо ли добавить ultralytics в requirements?

2023-05-29 18:58 UTC, ManVersusPerson reviewed
Думаю стоит добавить комментарии

2023-05-29 18:58 UTC, ManVersusPerson commented on model/model.py
> +    def get_predicred_result(self):
Поправить опечатку

2023-05-30 10:38 UTC, ExtensiveTree commented on requirements.txt
Вроде нужно еще и другие библиотеки сюда прописать

2023-05-30 10:42 UTC, amoonnra commented on requirements.txt
А какие?

2023-05-31 16:37 UTC, amoonnra commented on model/model.py
> +    def get_predicred_result(self):
Считаю что комментарии излишни в таком простом проекте и названия функций говорят, что делают. Но для единообразия добавлю их.

2023-05-31 16:55 UTC, amoonnra commented on requirements.txt
Жень, ты либо напиши какие на твой взгляд нужны еще библиотеки, либо поставь аппрув, если все устраивает. Чтобы не затягивать с этим.

2023-05-31 17:43 UTC, ManVersusPerson commented on api/api.py
> +    predicted_result = Model(file_buf).get_predicred_result()
тут вроде всё ещё опечатка в predicred

2023-05-31 17:45 UTC, ManVersusPerson requested changes
Поправить опечатку, в остальном вроде всё хорошо

2023-05-31 17:47 UTC, ManVersusPerson approved these changes

2023-06-05 17:00 UTC, merged